-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.account
(
    id bigint NOT NULL DEFAULT nextval('account_id_seq'::regclass),
    account_no integer,
    branch_id bigint,
    customer_id bigint,
    CONSTRAINT account_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.account_platform
(
    account_id bigint NOT NULL,
    platform_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.account_type
(
    id bigint NOT NULL DEFAULT nextval('account_type_id_seq'::regclass),
    accounttype character varying(255) COLLATE pg_catalog."default",
    account_id bigint,
    CONSTRAINT account_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.branches
(
    id bigint NOT NULL DEFAULT nextval('branches_id_seq'::regclass),
    city_name character varying(255) COLLATE pg_catalog."default",
    city_no integer,
    CONSTRAINT branches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    id bigint NOT NULL DEFAULT nextval('customer_id_seq'::regclass),
    customer_no integer,
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT customer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.operational_submitions
(
    id bigint NOT NULL DEFAULT nextval('operational_submitions_id_seq'::regclass),
    amount integer NOT NULL,
    operation_date date,
    operation_no integer,
    account_id bigint,
    customer_id bigint,
    platform_id bigint,
    CONSTRAINT operational_submitions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.platform
(
    id bigint NOT NULL DEFAULT nextval('platform_id_seq'::regclass),
    amount integer NOT NULL,
    operation_date date,
    operation_no integer,
    operation_platform character varying(255) COLLATE pg_catalog."default",
    operation_type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT platform_pkey PRIMARY KEY (id),
    CONSTRAINT uk_e8dxmanc4go6ensxys0f8my5f UNIQUE (operation_platform)
);

CREATE TABLE IF NOT EXISTS public.process_place
(
    id bigint NOT NULL DEFAULT nextval('process_place_id_seq'::regclass),
    process_place character varying(255) COLLATE pg_catalog."default",
    process_id bigint,
    CONSTRAINT process_place_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.process_type
(
    id bigint NOT NULL DEFAULT nextval('process_type_id_seq'::regclass),
    process_name character varying(255) COLLATE pg_catalog."default",
    process_id bigint,
    CONSTRAINT process_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.processes
(
    id bigint NOT NULL DEFAULT nextval('processes_id_seq'::regclass),
    process_date date,
    CONSTRAINT processes_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.account
    ADD CONSTRAINT fk7dxh569gmv7rae3kf0fm0wf59 FOREIGN KEY (branch_id)
    REFERENCES public.branches (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.account
    ADD CONSTRAINT fkfhh6otya6l3sdh1v6jut588tf FOREIGN KEY (customer_id)
    REFERENCES public.customer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.account_platform
    ADD CONSTRAINT fku31mqwua0b52mxq5diqdpa3q FOREIGN KEY (platform_id)
    REFERENCES public.platform (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.account_type
    ADD CONSTRAINT fkqqomsm2usbgr26kbpw145p4iw FOREIGN KEY (account_id)
    REFERENCES public.account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.operational_submitions
    ADD CONSTRAINT fk9c0sraq6nt4l67f2tm47e7cii FOREIGN KEY (platform_id)
    REFERENCES public.platform (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.process_place
    ADD CONSTRAINT fkioql24yq4r8ghm1qjthgms8k3 FOREIGN KEY (process_id)
    REFERENCES public.processes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.process_type
    ADD CONSTRAINT fkll7xgfdipwb259edpgp6t70ed FOREIGN KEY (process_id)
    REFERENCES public.processes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;